# Generated by Django 4.1.1 on 2022-09-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='spec_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('salary_from', models.PositiveSmallIntegerField()),
                ('salary_to', models.PositiveSmallIntegerField()),
                ('skills', models.CharField(max_length=240)),
                ('description', models.TextField(max_length=3000)),
                ('posted', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy_app.specialty')),
            ],
        ),
    ]
