# Generated by Django 4.1.1 on 2022-10-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_app', '0002_vacancy_is_published_alter_vacancy_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['posted']},
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.PositiveIntegerField(verbose_name='Зарплата от'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.PositiveIntegerField(verbose_name='Зарплата до'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(max_length=240, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy_app.specialty', verbose_name='Специализация'),
        ),
    ]
